// NOTE: This file aswell as the web.rs and wasm_api.rs files were fully generated by claude code
// NOTE: This was mostly done as an experiment by me to see how good it is at generating rust code
// NOTE: Please keep that in mind when writing/reviewing code in these section

//! Step-based interpreter for the WASM / web interface.
//!
//! ## Execution model
//!
//! Because WASM is single-threaded and cannot block, we use a *replay*
//! strategy instead of suspending the interpreter mid-stack:
//!
//! 1. Every call to `step()` re-runs the full program from the beginning.
//! 2. `input_log` holds all inputs the user has supplied so far.  On each
//!    replay these are served back in order.
//! 3. `output_pos` counts how many OUTPUT events have already been sent to the
//!    caller.  The replay skips that many outputs, then captures the next one
//!    and stops (via `ErrorType::StepOutput`).
//! 4. When the input log is exhausted mid-replay, the interpreter returns
//!    `ErrorType::StepNeedsInput` which `step()` converts to a
//!    `StepEvent::NeedsInput`.
//!
//! This is O(n²) in total statements executed, which is entirely acceptable
//! for educational Cambridge pseudocode programs.
//!
//! 5. `rand_log` holds every RAND value ever generated.  On replay `rand_pos`
//!    resets to 0 so the same sequence is produced.  New values are appended
//!    at the end of the log and written back to `StepInterpreter` after each
//!    replay, so they persist for subsequent calls to `step()`.
use std::cell::RefCell;
use std::collections::HashMap;
use std::rc::Rc;

use crate::errortype::ErrorType;
use crate::Inter::cps::Value;
use crate::Inter::interpreter::{Interpreter, ReplayContext, VirtualFile};
use crate::Parser::ast::Ast;

/// Events returned by [`StepInterpreter::step`].
///
/// Serialised to `{ type: "Output", value: "…" }` etc. for the WASM API.
#[derive(Debug, serde::Serialize)]
#[serde(tag = "type")]
pub enum StepEvent {
    /// An OUTPUT statement produced this line.
    Output { value: String },
    /// An INPUT statement is waiting for the given variable.
    /// Call [`StepInterpreter::supply_input`] then [`StepInterpreter::step`]
    /// again to resume.
    NeedsInput { variable: String },
    /// The program finished successfully.
    Done,
    /// The program terminated with an error.
    Error { message: String },
}

/// Drives a pseudocode program one event at a time.
pub struct StepInterpreter {
    /// Pre-parsed AST — shared by all replay runs without cloning.
    ast: Vec<Ast>,
    /// The program text, handed to each replay so runtime errors can show the offending line.
    source: String,
    /// Inputs supplied by the user, in order.
    input_log: Vec<String>,
    /// How many OUTPUT events have already been served to the caller.
    output_pos: usize,
    /// RAND values generated so far (persisted across replays for determinism).
    rand_log: Vec<Value>,
    /// Virtual filesystem state persisted across replays.
    virtual_fs: HashMap<String, VirtualFile>,
    /// Set to true once the program finishes or errors.
    done: bool,
}

impl StepInterpreter {
    /// Parse `source` and prepare for step-based execution.
    /// Returns an error string if lexing or parsing fails.
    pub fn new(source: &str) -> Result<Self, String> {
        use crate::Lexer::lexer::Lexer;
        use crate::Parser::parser::Parser;

        let lexer = Lexer::new(source.to_string());
        let tokens = lexer.tokenize().map_err(|e| e.to_string())?;

        let mut parser = Parser::new(tokens, source.to_string());
        let ast = parser.parse_statements().map_err(|e| e.to_string())?;

        Ok(StepInterpreter {
            ast,
            source: source.to_string(),
            input_log: Vec::new(),
            output_pos: 0,
            rand_log: Vec::new(),
            virtual_fs: HashMap::new(),
            done: false,
        })
    }

    /// Advance execution by one event.
    ///
    /// Replays the program from the start each time, replaying previous inputs
    /// and skipping already-served outputs, then captures the next new output
    /// or stops at the next INPUT that needs a value.
    pub fn step(&mut self) -> StepEvent {
        if self.done {
            return StepEvent::Done;
        }

        let vfs_rc = Rc::new(RefCell::new(self.virtual_fs.clone()));

        let ctx = Rc::new(RefCell::new(ReplayContext {
            inputs: self.input_log.clone(),
            input_pos: 0,
            output_skip: self.output_pos,
            rand_log: self.rand_log.clone(),
            rand_pos: 0,
            virtual_fs: Rc::clone(&vfs_rc),
        }));

        let mut interp = Interpreter::new_replay(self.source.clone(), Rc::clone(&ctx));
        let result = interp.interpret_slice(&self.ast);

        // Save any newly generated RAND values back so future replays are
        // deterministic.  This mirrors how input_log is updated via supply_input.
        self.rand_log = ctx.borrow().rand_log.clone();
        // Sync virtual FS state back so file contents persist across replays.
        self.virtual_fs = vfs_rc.borrow().clone();

        match result {
            Ok(()) => {
                // Program ran to completion without producing another output
                // or hitting an un-served input — we're done.
                self.done = true;
                StepEvent::Done
            }
            Err(e) => match e.error_type {
                ErrorType::StepOutput(value) => {
                    self.output_pos += 1;
                    StepEvent::Output { value }
                }
                ErrorType::StepNeedsInput(variable) => StepEvent::NeedsInput { variable },
                _ => {
                    // Genuine runtime / lexical / syntax error.
                    self.done = true;
                    StepEvent::Error {
                        message: e.to_string(),
                    }
                }
            },
        }
    }

    /// Provide the value for the most recently requested INPUT variable.
    /// Must be called after receiving a `StepEvent::NeedsInput`, before the
    /// next call to `step()`.
    pub fn supply_input(&mut self, value: String) {
        self.input_log.push(value);
    }

    /// Pre-load a file's contents into the virtual filesystem so the program
    /// can `OPENFILE … READ` and `READFILE` from it.
    /// Split `content` by `\n`; each element becomes one readable line.
    pub fn load_file(&mut self, name: &str, content: &str) {
        use crate::Parser::ast::FileMode;
        let lines: Vec<String> = content.split('\n').map(|s| s.to_string()).collect();
        self.virtual_fs.insert(
            name.to_string(),
            VirtualFile {
                lines,
                read_pos: 0,
                write_pos: 0,
                mode: FileMode::Read,
                open: false,
                was_written: false,
            },
        );
    }

    /// Return the current contents of a virtual file joined by `\n`, or
    /// `None` if no such file exists in the virtual filesystem.
    pub fn get_file(&self, name: &str) -> Option<String> {
        self.virtual_fs.get(name).map(|vf| vf.lines.join("\n"))
    }

    /// Return the names of all files that have been written or appended to
    /// during execution.
    pub fn list_written_files(&self) -> Vec<String> {
        self.virtual_fs
            .iter()
            .filter(|(_, vf)| vf.was_written)
            .map(|(name, _)| name.clone())
            .collect()
    }
}
