// NOTE: This file aswell as the step_interpreter.rs and wasm_api.rs files were fully generated by claude code
// NOTE: This was mostly done as an experiment by me to see how good it is at generating rust code
// NOTE: Please keep that in mind when writing/reviewing code in these section

use std::sync::mpsc::{self, Receiver, Sender};
use std::thread;

/// Events emitted by the interpreter to the web layer.
#[derive(Debug)]
pub enum WebEvent {
    /// A line of output produced by an OUTPUT statement.
    Output(String),
    /// The interpreter is paused waiting for the user to supply a value for
    /// the given variable.  Send the response string via the `input_tx`
    /// channel returned by [`run_web`] to resume execution.
    NeedsInput { variable: String },
    /// The program finished successfully.
    Done,
    /// The program terminated with an error.
    Error(String),
}

/// Channels owned by the interpreter while it runs in web mode.
pub struct WebContext {
    pub event_tx: Sender<WebEvent>,
    pub input_rx: Receiver<String>,
}

// Manual Debug impl because Receiver doesn't print anything useful.
impl std::fmt::Debug for WebContext {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("WebContext").finish_non_exhaustive()
    }
}

/// Run a pseudocode program in web mode.
///
/// Returns `(handle, input_tx, event_rx)`:
///
/// - Read `WebEvent`s from `event_rx` to drive the UI.
/// - When you receive `NeedsInput { variable }`, show an input prompt, then
///   send the user's response string via `input_tx` to resume the interpreter.
/// - `Done` or `Error` signals the end of execution; join `handle` afterwards.
///
/// Each call spins up an independent thread so multiple programs can run
/// concurrently, each with its own channel pair.
pub fn run_web(source: String) -> (thread::JoinHandle<()>, Sender<String>, Receiver<WebEvent>) {
    let (event_tx, event_rx) = mpsc::channel::<WebEvent>();
    let (input_tx, input_rx) = mpsc::channel::<String>();

    let handle = thread::spawn(move || {
        use crate::Inter::interpreter::Interpreter;
        use crate::Lexer::lexer::Lexer;
        use crate::Parser::parser::Parser;

        let lexer = Lexer::new(source.clone());
        let tokens = match lexer.tokenize() {
            Ok(t) => t,
            Err(e) => {
                let _ = event_tx.send(WebEvent::Error(e.to_string()));
                return;
            }
        };

        let mut parser = Parser::new(tokens, source.clone());
        let ast = match parser.parse_statements() {
            Ok(a) => a,
            Err(e) => {
                let _ = event_tx.send(WebEvent::Error(e.to_string()));
                return;
            }
        };

        let mut interpreter = Interpreter::new_web(
            source,
            WebContext {
                event_tx: event_tx.clone(),
                input_rx,
            },
        );

        match interpreter.interpret(ast) {
            Ok(_) => {
                let _ = event_tx.send(WebEvent::Done);
            }
            Err(e) => {
                let _ = event_tx.send(WebEvent::Error(e.to_string()));
            }
        }
    });

    (handle, input_tx, event_rx)
}
