// NOTE: This file aswell as the web.rs and step_interpreter.rs files were fully generated by claude code
// NOTE: This was mostly done as an experiment by me to see how good it is at generating rust code
// NOTE: Please keep that in mind when writing/reviewing code in these section

//! WASM bindings — compiled only when targeting `wasm32`.
//!
//! Build with:
//!   wasm-pack build --target web --out-dir web/pkg

#![cfg(target_arch = "wasm32")]

use crate::Inter::step_interpreter::StepInterpreter;
use wasm_bindgen::prelude::*;

/// Drives a Cambridge pseudocode program from JavaScript one event at a time.
///
/// ```js
/// const runner = new WebRunner(source);
/// while (true) {
///     const event = runner.step();
///     if (event.type === "Output")      { console.log(event.value); }
///     else if (event.type === "NeedsInput") {
///         runner.supply_input(await promptUser(event.variable));
///     } else if (event.type === "Done")  { break; }
///     else if (event.type === "Error")   { console.error(event.message); break; }
/// }
/// ```
#[wasm_bindgen]
pub struct WebRunner {
    inner: StepInterpreter,
}

#[wasm_bindgen]
impl WebRunner {
    /// Parse `source` and prepare for execution.
    ///
    /// Throws a JS error string if the source fails to lex or parse.
    #[wasm_bindgen(constructor)]
    pub fn new(source: &str) -> Result<WebRunner, JsValue> {
        StepInterpreter::new(source)
            .map(|inner| WebRunner { inner })
            .map_err(|e| JsValue::from_str(&e))
    }

    /// Advance execution by one event.
    ///
    /// Returns a plain JS object with a `type` field:
    /// - `{ type: "Output",     value: string }`
    /// - `{ type: "NeedsInput", variable: string }`
    /// - `{ type: "Done" }`
    /// - `{ type: "Error",      message: string }`
    pub fn step(&mut self) -> JsValue {
        let event = self.inner.step();
        serde_wasm_bindgen::to_value(&event).unwrap_or_else(|e| {
            let obj = js_sys::Object::new();
            let _ = js_sys::Reflect::set(
                &obj,
                &JsValue::from_str("type"),
                &JsValue::from_str("Error"),
            );
            let _ = js_sys::Reflect::set(
                &obj,
                &JsValue::from_str("message"),
                &JsValue::from_str(&e.to_string()),
            );
            obj.into()
        })
    }

    /// Supply the user's response to the most recent `NeedsInput` event.
    /// Must be called before the next `step()`.
    pub fn supply_input(&mut self, value: &str) {
        self.inner.supply_input(value.to_string());
    }

    /// Pre-load a file into the virtual filesystem before execution begins.
    ///
    /// Call once per file before the first `step()`. `content` is split by
    /// `\n`; each element becomes one line readable via `READFILE`.
    pub fn load_file(&mut self, name: &str, content: &str) {
        self.inner.load_file(name, content);
    }

    /// Read back the current contents of a virtual file as a single string
    /// (lines joined by `\n`). Returns `undefined` if the file does not exist.
    pub fn get_file(&mut self, name: &str) -> Option<String> {
        self.inner.get_file(name)
    }

    /// Returns a JS array of filenames that were written or appended to
    /// during execution.
    pub fn list_written_files(&mut self) -> JsValue {
        let names = self.inner.list_written_files();
        serde_wasm_bindgen::to_value(&names).unwrap_or_else(|e| {
            let obj = js_sys::Object::new();
            let _ = js_sys::Reflect::set(
                &obj,
                &JsValue::from_str("error"),
                &JsValue::from_str("serialization_error"),
            );
            let _ = js_sys::Reflect::set(
                &obj,
                &JsValue::from_str("message"),
                &JsValue::from_str(&e.to_string()),
            );
            obj.into()
        })
    }
}
